##################################################################
#        VerCode | Wejd藕 w iat nowoczesnej technologii!         #
#          VerCode-TPA | Plugin na TPA, jak z anarchii           #
#                Plik configuracyjny: config.yml                 #
#                                                                #
#                    Autor pluginu: xMateusZG                    #
##################################################################

# {prefix} - prefix wiadomosci
# {player} - gracz poboczny (np. kt贸ry otrzyma probe o teleportacje)
# {sending_player} - gracz gowny (np. osoba kt贸ra wysya probe o teleportacje)
# {active_requests} - aktywne proby o teleportacje
# {time_teleportation} - czas teleportacji

# Opcje
options:
  # Prefix (Zmienna: {prefix}
  prefix: "&8[&3VerCode &7| &bTPA&8|&r "

  # Czas trwania teleportacji
  teleportation_duration:
    # Dla gracza (s = sekundy, m = minuty, zalecany s)
    player: 5s
    # Gracza z permisj (vercode.tpa.teleport.speed, OP)
    permission: 1s

  # Zablokowane wiaty (Zostaw puste je偶eli chcesz wyczy t opcj)
  locked_worlds: [test1, test2]

  # Czy gracz ma teleportowa si w miejsce gdzie stoi gracz (true),
  # lub czy gracz ma teleportowa w miejsce w kt贸rym sta poprzedni gracz
  # czyli np. jak gracz kt贸ry teleportowa danego gracza si ruszy to on
  # przeteleportuje si w miejsce w kt贸rym sta wczeniej podczas akceptacji (false)
  teleport_player_location: false

  # D藕wiki pluginu
  sounds:
    tpa_send: "ENTITY_EXPERIENCE_ORB_PICKUP"
    tpa_receive: "ENTITY_PLAYER_LEVELUP"
    accept: "UI_TOAST_CHALLENGE_COMPLETE"
    deny: "BLOCK_NOTE_BLOCK_BASS"
    cancel: "ENTITY_VILLAGER_NO"
    teleport: "ENTITY_ENDERMAN_TELEPORT"

# Wiadomosci dla teleportacji
messages_teleportation:
  sending_request:
    chat:
      - ""
      - ""
      - "{prefix} &aWysae probe o teleportacje"
      - " &adla gracza: &2{player}&a!"
      - ""
      - " &eWpisz: &6&n/tpadeny <nick / * / nic>&e,"
      - " &eaby odwoa prob!"

    title:
      title: "&8[&2&8] &aTELEPORTACJA &8[&2&8]"
      subtitle: "&eWysano probe o teleportacje!"
      # Czas trwania title
      message_duration: 5s

  # Otrzymanie proby o teleportacje
  receiving_request_teleportation:
    chat:
      - ""
      - ""
      - "{prefix} &aOtrzymae probe o teleportacje!"
      - " &aod gracza: &2{sending_player}"
      - ""
      - " &eAby zaakceptowa wpisz: &6/tpaaccept <nick / * / nic>&e!"
      - " &elub kliknij: {button1}&e / {button2}&e!"

    bossbar:
      message: "&aOtrzymae prob o teleportacje od: &2&n{player}&a. &c[Aktywne proby: {active_requests}]"
      # Kolor (Wpisuj: Nazwe koloru np: blue, lub &{liczba}.
      # Mozesz r贸wie偶 zrobi animacje: [kolor1, kolor2....]
      color: [BLUE, AQUA]
      # Czas w kt贸rym czasie zmieniaj sie kolory (Najlepiej podawa w sekundach = s
      # lub milisekundach = mm, jezeli masz 1 kolor wpisz: false]
      color_changing_time: 10mm

  # Zaakcepotwanie teleportacji
  accepting_request:
    chat:
      - ""
      - ""
      - "{prefix} &aZaakceptowae probe o teleportacje!"
      - " &aod gracza: {player}"
    title: "&8[&2&8] &aTELEPORTACJA &8[&2&8]"
    subtitle: "&anastpi za: {time_teleportation}!"

  # Odrzucenie teleportacji
  rejection_request:
    chat:
      - ""
      - ""
      - "{prefix} &cOdrzucie probe o teleportacje!"
      - " &aod gracza: {player}"

  # Przerwanie teleportacji gdy gracz si poruszy z bloku na kt贸rym stoi (nie kamer)
  after_moving:
    title: "&8[&2&8] &aTELEPORTACJA &8[&2&8]"
    subtitle: "&cprzerwana! Poruszye si "

# Przysiski (Mo偶esz dodawa swoje
buttons:
  # Akceptacji
  accept:
    # Zmienna
    variable: {button1}
    # Text tej go przysisku
    text: "&2&l[]"
    # Komenda jaka si wykonuje gdy kliknie sie na wiadomoc (guzik)
    command_executes:
      - tpaaccept {player}

  # Odrzucenia
  deny:
    # Zmienna
    variable: {button2}
    # Text tej go przysisku
    text: "&3&l[]"
    # Komenda jaka si wykonuje gdy kliknie sie na wiadomoc (guzik)
    command_executes:
      - tpadeny {player}
